version: "2.1"
services:
  mypostgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    healthcheck:
      test: "exit 0"
  myapp:
    image: servian/myapp:v2
    ports:
      - 3000:3000
    depends_on: 
      mypostgres:
        condition: service_healthy