version: "3"
services:
  mypostgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
  myapp:
    image: servian:v7
    ports:
      - 3000:3000
